# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31882e5bf69144b1c9dc8e44b0af55e2cddab17f35bb3fa85d52773156a0897b7655a21d52916012c3f92359fb3982203c46f7db535faca8b69d4b0f29810228

test:
  secret_key_base: 275d29edd11efcd60e84b33c386df214f0034fff599ef70bcadf880b1c550f6b915e691aca4b4ec9a348fb3889c5fbe6764e263b91b1ca21b1ce73723729af49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
